version: "3"

services:

    php:
        image: wodby/php:$PHP_TAG
        container_name: "${PROJECT_NAME}_php"
        restart: always
        environment:
            PHP_FPM_USER: wodby
            PHP_FPM_GROUP: wodby
        volumes:
            - ./public:/var/www/html:cached

    nginx:
        image: wodby/nginx:$NGINX_TAG
        container_name: "${PROJECT_NAME}_nginx"
        restart: always
        depends_on:
            - php
        environment:
            NGINX_BACKEND_HOST: php
            NGINX_VHOST_PRESET: php
        volumes:
            - ./public:/var/www/html:cached
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${PROJECT_NAME}_http.rule=Host(`${PROJECT_BASE_URL}`,`www.${PROJECT_BASE_URL}`)"
            - "traefik.http.routers.${PROJECT_NAME}_http.entrypoints=web"
            - "traefik.http.routers.${PROJECT_NAME}_http.middlewares=${PROJECT_NAME}_https_redirect"
            - "traefik.http.routers.${PROJECT_NAME}_https.rule=Host(`${PROJECT_BASE_URL}`,`www.${PROJECT_BASE_URL}`)"
            - "traefik.http.routers.${PROJECT_NAME}_https.entrypoints=websecure"
            - "traefik.http.routers.${PROJECT_NAME}_https.tls=true"
            - "traefik.http.routers.${PROJECT_NAME}_https.tls.certresolver=myresolver"
            - "traefik.http.routers.${PROJECT_NAME}_https.middlewares=${PROJECT_NAME}_www_redirect"
            - "traefik.http.middlewares.${PROJECT_NAME}_https_redirect.redirectscheme.scheme=https"
            - "traefik.http.middlewares.${PROJECT_NAME}_https_redirect.redirectscheme.permanent=true"
            - "traefik.http.middlewares.${PROJECT_NAME}_www_redirect.redirectregex.regex=^(https?)://${PROJECT_BASE_URL}/(.*)$$"
            - "traefik.http.middlewares.${PROJECT_NAME}_www_redirect.redirectregex.replacement=$${1}://www.${PROJECT_BASE_URL}/$${2}"
            - "traefik.http.middlewares.${PROJECT_NAME}_www_redirect.redirectregex.permanent=true"

