version: "3"

services:

    php:
        image: wodby/php:$PHP_TAG
        container_name: "${PROJECT_NAME}_php"
        restart: always
        environment:
            PHP_FPM_USER: wodby
            PHP_FPM_GROUP: wodby
        volumes:
            - ./:/var/www/html:cached

    nginx:
        image: wodby/nginx:$NGINX_TAG
        container_name: "${PROJECT_NAME}_nginx"
        restart: always
        depends_on:
            - php
        environment:
            NGINX_BACKEND_HOST: php
            NGINX_VHOST_PRESET: php
            NGINX_SERVER_ROOT: /var/www/html/public
        volumes:
            - ./:/var/www/html:cached
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${PROJECT_BASE_URL}`,`www.${PROJECT_BASE_URL}`)"
              #- "traefik.http.routers.${PROJECT_NAME}_nginx.middlewares=${PROJECT_NAME}_nginx_redirect"
            - "treafik.http.middlewares.${PROJECT_NAME}_nginx_redirect.redirectregex.regex='^http://${PROJECT_BASE_URL}/(.*)$$'"
            - "traefik.http.middlewares.${PROJECT_NAME}_nginx_redirect.redirectregex.replacement=http://www.${PROJECT_BASE_URL}/$${1}"

